### ISSUE TITLE
Deploying without serverless framework

### ISSUE THREAD

**Issue by boblund** [JamesKyburz/aws-lambda-ws-server#4]
Hi,

Nice repo. Just what I need. If I want to deploy in AWS without serverless it looks like I specify a function based on the code in your usage  example as the backend lambda for all routes: $connect, $disconnect, $default, message (and any other custom routes). Is this correct.

Thanks,
Bob

**Comment by JamesKyburz** [comment]
That is correct, although you don't have to have the same lambda for all events.

If you're not using the serverless framework then what ever you use will need to setup the API Gateway V2 with the route key along with the $connect, $disconnect and $default and trigger. My example used $request.body.message for the routing key.

Pull requests are welcome showing other ways of deploying this, I just chose what I am familiar with :)
